# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: prod

wylie:
    datasource:
        default:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://10.1.30.10:3306/hansot
            username: hansot_user
            password: hansot_user!230
            maximum-pool-size: 5
    site:
            domain: https://www.hsd.co.kr
            url-pc: https://www.hsd.co.kr
            viewMode: desktop
    file-upload:
            filepath: https://www.hsd.co.kr/images
            location: /image
    siren-cert:
            id: SCPO001
            srvNoForJoin: '013001'
            srvNoForLogin: '013004'
