# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: hsd-pc-web
    main:
      web-application-type: none
    mvc:
        favicon:
            enabled: false
        view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
#        resources:
#          static-locations: src/main/webapp/
    http:
      encoding:
        charset: UTF-8
        enabled: true
    velocity:
      enabled: false

multipart:
    max-file-size: 50MB
    max-request-size: 100MB


server:
  servlet:
    application-display-name: hsd-pc-web
  port: 8888